### ISSUE TITLE
Cannot Get Angular Profiles / CiviVolunteer to work on Joomla 2.5

### ISSUE THREAD

**Issue by penguintrax** [ginkgostreet/org.civicrm.angularprofiles#11]
I can create a volunteer project, roles, and relationships. When I attempt to add the time slots, etc., the system just hangs. Below are the errors being shown in console. Is the problem Joomla 2.5 or something else?  Thank you.

```
Failed to load resource: the server responded with a status of 404 (Category not found)
angular.js:11706 TypeError: b.indexOf is not a function
    at d.b (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:2:6988)
    at d.initContainerWidth (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:2:7172)
    at d.initContainer (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:2:13014)
    at d.init (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:1:19472)
    at HTMLSelectElement.<anonymous> (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:2:31028)
    at Function.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=v9Kok:2:2975)
    at m.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=v9Kok:2:835)
    at m.a.fn.select2 (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:2:30773)
    at HTMLSelectElement.<anonymous> (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/js/Common.js?r=v9Kok:412:11)
    at Function.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=v9Kok:2:2975) <select class="big crm-form-select crm-vol-beneficiary ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope" crm-ui-select="{placeholder: ts('Filter by Beneficiary'), allowClear:true}" ng-options="key as value.display_name for (key , value) in beneficiaries" ng-model="searchParams.beneficiaries" tabindex="-1" title="">(anonymous function) @ angular.js:11706
angular.js:11706 TypeError: b.indexOf is not a function
    at d.b (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:2:6988)
    at d.initContainerWidth (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:2:7172)
    at d.initContainer (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:2:13014)
    at d.init (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:1:19472)
    at HTMLSelectElement.<anonymous> (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:2:31028)
    at Function.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=v9Kok:2:2975)
    at m.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=v9Kok:2:835)
    at m.a.fn.select2 (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=v9Kok:2:30773)
    at HTMLSelectElement.<anonymous> (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/js/Common.js?r=v9Kok:412:11)
    at Function.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=v9Kok:2:2975) <select class="big crm-form-select crm-vol-campaign ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope" crm-ui-select="{placeholder: ts('Filter by Campaign'), allowClear:true}" ng-change="clearCampaign()" ng-options="key as value.title for (key , value) in campaigns" ng-model="searchParams.campaign_id" tabindex="-1" title="">(anonymous function) @ angular.js:11706
select2.min.js?r=v9Kok:2 Uncaught TypeError: b.indexOf is not a function
https://www.shomreitorahonline.org/media/civicrm/styles/ Failed to load resource: the server responded with a status of 404 (Category not found)
```

**Comment by universalhandle** [comment]
It's not obvious to me from your console dump what the problem is. However, based on your description of when the problem occurs, this does not appear to be a problem with Angular Profiles, whose primary job in CiviVolunteer is to properly display the profile selection widget.

I think your message suggests that the Angular-based interfaces of CiviVolunteer (e.g., civicrm/vol/#/volunteer/manage, civicrm/vol/#/volunteer/manage/0, civicrm/vol/#/volunteer/opportunities) are working. It would be useful to know if any of the BackboneJS-based interfaces work. A few ways to test that out: from civicrm/vol/#/volunteer/manage click "Define Volunteer Opportunities" or "Assign Volunteers" -- these links should open modals that render a large table/form and a drag-and-drop screen, respectively. If these screens aren't working, based on your error message, I'd guess that there's a JavaScript conflict between CiviCRM and Joomla around BackboneJS or underscore or some other library (i.e., different global objects sharing the same namespace).

It would also help to know the versions of CiviCRM and CiviVolunteer that you're running.

**Comment by penguintrax** [comment]
Thanks for the prompt reply. Using latest CiviCRM (4.7.10) and latest CiviVolunteer.

I'll try the troubleshooting steps you listed and let you know what happens.

Thank you!

**Comment by penguintrax** [comment]
Tried your suggestion and the modal appears, but anything that should be selectable, like the drag&drop or even the 'done' button is disabled.

Here is the error log in case it is of help:

> TypeError: b.indexOf is not a function
>     at d.b (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:2:6988)
>     at d.initContainerWidth (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:2:7172)
>     at d.initContainer (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:2:13014)
>     at d.init (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:1:19472)
>     at HTMLSelectElement.<anonymous> (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:2:31028)
>     at Function.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=fBDB3:2:2975)
>     at m.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=fBDB3:2:835)
>     at m.a.fn.select2 (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:2:30773)
>     at HTMLSelectElement.<anonymous> (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/js/Common.js?r=fBDB3:412:11)
>     at Function.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=fBDB3:2:2975) <select class="big crm-form-select crm-vol-beneficiary ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope" crm-ui-select="{placeholder: ts('Filter by Beneficiary'), allowClear:true}" ng-options="key as value.display_name for (key , value) in beneficiaries" ng-model="searchParams.beneficiaries" tabindex="-1" title="">(anonymous function) @ angular.js:11706(anonymous function) @ angular.js:8619Z @ angular.js:8283I @ angular.js:7791g @ angular.js:7140(anonymous function) @ angular.js:7019(anonymous function) @ angular.js:7158h @ angular.js:7818link @ angular.js:25507Z @ angular.js:8281I @ angular.js:7791g @ angular.js:7140I @ angular.js:7786(anonymous function) @ angular.js:8021(anonymous function) @ angular.js:13318$eval @ angular.js:14570$digest @ angular.js:14386(anonymous function) @ angular.js:14609e @ angular.js:4940(anonymous function) @ angular.js:5328
> angular.js:11706 TypeError: b.indexOf is not a function
>     at d.b (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:2:6988)
>     at d.initContainerWidth (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:2:7172)
>     at d.initContainer (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:2:13014)
>     at d.init (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:1:19472)
>     at HTMLSelectElement.<anonymous> (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:2:31028)
>     at Function.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=fBDB3:2:2975)
>     at m.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=fBDB3:2:835)
>     at m.a.fn.select2 (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/select2/select2.min.js?r=fBDB3:2:30773)
>     at HTMLSelectElement.<anonymous> (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/js/Common.js?r=fBDB3:412:11)
>     at Function.each (https://www.shomreitorahonline.org/administrator/components/com_civicrm/civicrm/bower_components/jquery/dist/jquery.min.js?r=fBDB3:2:2975) <select class="big crm-form-select crm-vol-campaign ng-pristine ng-untouched ng-valid ng-scope ng-isolate-scope" crm-ui-select="{placeholder: ts('Filter by Campaign'), allowClear:true}" ng-change="clearCampaign()" ng-options="key as value.title for (key , value) in campaigns" ng-model="searchParams.campaign_id" tabindex="-1" title="">(anonymous function) @ angular.js:11706(anonymous function) @ angular.js:8619Z @ angular.js:8283I @ angular.js:7791g @ angular.js:7140(anonymous function) @ angular.js:7019(anonymous function) @ angular.js:7158h @ angular.js:7818link @ angular.js:25507Z @ angular.js:8281I @ angular.js:7791g @ angular.js:7140I @ angular.js:7786(anonymous function) @ angular.js:8021(anonymous function) @ angular.js:13318$eval @ angular.js:14570$digest @ angular.js:14386(anonymous function) @ angular.js:14609e @ angular.js:4940(anonymous function) @ angular.js:5328

**Comment by universalhandle** [comment]
Doesn't really tell me anything new. If anything, confirms my hunch that all the JavaScript on the page isn't playing nice together.

I note that all the files in the stack trace are "deep," meaning they are all libraries and not application code. I can't tell from looking at this what code in CiviVolunteer is kicking off the code that ultimately fails. This furthers my hunch that the problem lies not in a logic error in either of the CiviCRM extensions but in something specific to your instance (e.g., poorly encapsulated JavaScript in a theme).

At this point I think you have two courses of action:
- The WordPress approach to debugging: turn off as many Joomla components, themes, plugins, etc. as possible. If CiviVolunteer behaves correctly in as close to a vanilla state as you can get your site, enable the components one by one until you find the culprit.
- Hire a developer to help you debug this.

Sorry I couldn't be of more help.

**Comment by penguintrax** [comment]
Thanks, Frank. that's the next step.

I even tried installing the two extensions in a Wordpress intall and I'm getting all sorts of errors when CiviVolunteer is installing.  None of the solutions in Stackexchange worked. Le Sigh.
